# Environnement de l'image : Node v22 - Linux Alpine (version légère de Linux)
FROM node:22-alpine

# Répertoire de travail dans le conteneur
WORKDIR /app

# Copier les fichiers package.json et package-lock.json : de l'env local vers l'image Docker
COPY package*.json ./

# Installer les dépendances dans l'image (clean install)
RUN npm ci

# Copier tout le code source du projet dans l'image
COPY . .

# Exposer le port de l'App Vite
EXPOSE 5173

# Lancer l'App en mode DEV après création de l'image
# --host et 0.0.0.0 : permet à l'App d’être accessible depuis l'extérieur du container
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]