# Environnement de l'image : Node v22 - Linux Alpine (version légère de Linux)
FROM node:22-alpine

# Répertoire de travail dans le conteneur
WORKDIR /app

# Copier les fichiers package.json et package-lock.json : de l'env local vers l'image Docker
COPY package*.json ./

# Installer les dépendances dans l'image
RUN npm install

# Copier tout le code source du projet dans l'image
COPY . .

# Exposer le port du serveur
EXPOSE 4000

# Lancer Node en mode DEV après création de l'image
# --host : permet au serveur d’être accessible depuis l'extérieur du container
CMD ["npm", "run", "dev", "--", "--host"]