/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary-fixed-dim': '#95d4b3',
        'surface-container-lowest': '#ffffff',
        'on-surface-variant': '#414844',
        tertiary: '#401b1b',
        'surface-tint': '#2c694e',
        'on-secondary': '#ffffff',
        'on-primary-fixed-variant': '#0e5138',
        'surface-container-high': '#e7e8e9',
        primary: '#002d1c',
        'on-surface': '#191c1d',
        'on-tertiary-container': '#d29895',
        'on-primary-container': '#76b394',
        'surface-dim': '#d9dadb',
        'surface-container-low': '#f3f4f5',
        'on-tertiary-fixed': '#331111',
        'surface-variant': '#e1e3e4',
        'on-primary-fixed': '#002114',
        'primary-fixed': '#b1f0ce',
        'on-secondary-container': '#58685f',
        'error-container': '#ffdad6',
        'on-secondary-fixed': '#101e17',
        'surface-container-highest': '#e1e3e4',
        'inverse-primary': '#95d4b3',
        'on-error-container': '#93000a',
        'secondary-container': '#d5e7db',
        'surface-container': '#edeeef',
        'secondary-fixed-dim': '#b9cbbf',
        background: '#f8f9fa',
        'on-primary': '#ffffff',
        outline: '#717973',
        error: '#ba1a1a',
        'tertiary-fixed-dim': '#f5b7b4',
        'primary-container': '#00452e',
        'on-secondary-fixed-variant': '#3b4a42',
        'on-tertiary-fixed-variant': '#673a39',
        secondary: '#526259',
        'tertiary-container': '#5a302f',
        'tertiary-fixed': '#ffdad8',
        'secondary-fixed': '#d5e7db',
        'inverse-on-surface': '#f0f1f2',
        'inverse-surface': '#2e3132',
        surface: '#f8f9fa',
        'on-tertiary': '#ffffff',
        'on-error': '#ffffff',
        'on-background': '#191c1d',
        'outline-variant': '#c1c8c2',
        'surface-bright': '#f8f9fa',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Newsreader', 'serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
};
