services:
  # Database : PostgreSQL
  postgres_db:
    image: postgres:16-alpine # version légère
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data # Données persistentes entre les redémarrages du container

  # Backend : Node / Express
  backend:
    build:
      context: ./backend # localisation du code source
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app # synchronise le code local avec le container
      - /app/node_modules # pour éviter que le dossier node_modules local n'écrase celui du conteneur
      - ./shared:/app/shared # permet d'accéder aux ressources partagées
    env_file:
      - ./backend/.env # injecter les variables d'env du backend
    environment:
      - CHOKIDAR_USEPOLLING=true # pour hot-reload
    ports:
      - '${SERVER_PORT:-4000}:${SERVER_PORT:-4000}'
    depends_on:
      - postgres_db # le backend démarre après la BDD

  # Frontend : Vite + React/TS
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./shared:/app/shared
    env_file:
      - ./frontend/.env
    environment:
      - CHOKIDAR_USEPOLLING=true # pour hot-reload
    ports:
      # Port Vite par défaut
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    depends_on:
      - backend # le frontend démarre après le backend

# Volumes persistants
volumes:
  postgres_data:
